"use strict";
let countries = [];
countries.push("Pakistan");
countries.push("Bangladesh");
countries.push("Afghanistan");
countries.push('Srilanka');
countries.push('Russia');
countries.push('Australia');
countries.push('China');
countries.push('Japan');
console.log(countries);
